---
  - name: Update apt cache and install Nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Copy projectA.j2 file of NGINX
    template:
      src: ../files/projectA.j2
      dest: /etc/nginx/conf.d/myApp.conf
      mode: preserve
    

  - name: Copy default.j2 file of NGINX
    template:
      src: ../files/default.j2
      dest: /etc/nginx/conf.d/default.conf
      mode: preserve
    

  - name: Restart Nginx service
    become: true
    systemd:
      name: nginx
      state: restarted