---
  - name: Update apt cache and install Nginx
    become: true
    apt:
      name: nginx
      state: latest
      update_cache: yes

 # - name: Copy projectA.j2 file of NGINX
  #  template:
   #   src: ../files/projectA.j2
    #  dest: /etc/nginx/conf.d/myApp.conf
     # mode: preserve

  #- name: Copy website files to the server's document root
   # copy:
    #  src: /vagrant/app/public_html
     # dest: /var/www/html
      #mode: preserve

  - name: Remove Nginx default file
    become: true
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    

  - name: Copy default.j2 file of NGINX
    template:
      src: ../files/default.j2
      dest: /etc/nginx/conf.d/default.conf
      mode: preserve
    

  - name: Restart Nginx service
    become: true
    systemd:
      name: nginx
      state: restarted