FROM nginx:latest

# Copy the nginx configuration file into the Docker container nginx configuration file
COPY /provision/projectB.conf /etc/nginx/conf.d/default.conf

# Expose nginx port
EXPOSE 80

# Start the nginx service
# -g -> global config 
# daemon off; -> makes nginx run in the foreground (not as a background task) = nginx runs as main process
CMD ["nginx", "-g", "daemon off;"]

# build: docker build -t nginx .
# run:   docker run -it --rm --name Nginx nginx  
