version: '3.8'

services:
  app:
    build:
      context: /app
      dockerfile: Dockerfile.app
    volumes:
      - app_gallery:/usr/src/webapp/public_html/data/gallery

  db:
    build:
      context: /provision
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  websockets:
    build:
      context: /ws
      dockerfile: Dockerfile.websockets
    ports:
      - 8000:8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      - app_gallery:/usr/src/webapp/public_html/data/gallery:ro # read only

volumes:
  app_gallery:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/public_html/data/gallery'
# build:  docker-compose build
# run:    docker-compose up
