- hosts: web
- name: Install PHP-FPM and necessary modules
  apt:
    name:
      - php
      - php-fpm
      - php-common
      - php-cli
      - php-mysql
      - php-pgsql
      - php-pdo
      - php-mbstring
      - php-zip
      - zip
      - unzip
    state: present

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Run Composer installer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  become: true

- name: Update Composer dependencies
  command: composer install
  args:
    chdir: /usr/src/webapp
  become: true

- name: Ansible Copy Example Local to Remote
  hosts: web
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src:  ../app/.
        dest: /usr/src/webapp/
        owner: nginx
        group: nginx      
        mode: 0644